version: "3.9"
services:
  web:
    build:
      context: ./web
      dockerfile: ./dockerfile
    ports:
      - 3000:3000

  worker:
    build:
      context: ./pipeline
      dockerfile: ./dockerfile
    deploy:
      mode: replicated
      replicas: 3
