name: ci

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Build and push: Oloom Web"
        uses: docker/build-push-action@v6
        with:
          context: ./web
          platforms: linux/amd64
          push: true
          tags: holyc0w/oloom-web:latest, holyc0w/oloom-web:${{ github.sha }}

      - name: "Build and push: Oloom Worker"
        uses: docker/build-push-action@v6
        with:
          context: ./pipeline
          platforms: linux/amd64
          push: true
          tags: holyc0w/oloom-worker:latest, holyc0w/oloom-worker:${{ github.sha }}
