FROM oven/bun:latest
# TODO: Fix the certificate issue, opting for insecure http connection for minio
# # Install CA certificates. You might need to adjust the path depending on your base image.
# RUN apt-get update && apt-get install -y ca-certificates
COPY . .
RUN bun install
EXPOSE 3000
ENV SKIP_ENV_VALIDATION=1
RUN bun run build
CMD ["bun", "run", "start"]
